- docs/api.rst
Mention that a tablename will be generated if the model sets a primary key and doesn't otherwise set a tablename.  Related to #248.  Addresses #213.
> document automatic tablename

- README
Because currently it's available but not documented.
> Add additional note about tox

- docs/conf.py
- docs/config.rst
- docs/signals.rst
- flask_sqlalchemy/__init__.py
- test_sqlalchemy.py
Use `before_flush` event to track changes.  This removes the need for mapper events.  It also makes the `before_models_committed` event work, addressing #90, #95, #150, and #237.  Instances are identified using SQLAlchemy's `identity_key` if possible rather than just primary key, to guard against separate models with the same keys, addressing #78 and #156.
Only register modification tracking events if the configuration enables them.  Previously, the events would always be registered but wouldn't do anything.  This reduces the overhead of handling each callback when not needed.  The events are registered on specific sessions, not the top-level session, and registration creates the `_model_changes` property, so there is no need to guard against this not existing anymore.  This better …
> Fix and deprecate change tracking

- docs/contexts.rst
- docs/quickstart.rst
- flask_sqlalchemy/__init__.py
- test_sqlalchemy.py
See: https://github.com/mitsuhiko/flask/issues/1135
Not sure if we can/need to also change this in the documentation generation.
> Change import to reflect deprecated ext format

- flask_sqlalchemy/__init__.py
- test_sqlalchemy.py
This allows `query.paginate` to be called without arguments in common cases.  It will grab the `page` and `per_page` query parameters if there is a request context.  Otherwise, it defaults to page 1, 20 per page.
> Get paginate args from request args

- CHANGES
- docs/config.rst
- flask_sqlalchemy/__init__.py
- test_sqlalchemy.py
> Add custom meta data parameter

- docs/models.rst
Example table name used in the models.rst is Address, not Article, so I fixed it.
> docs: fixed a misc typo in models.rst

- flask_sqlalchemy/__init__.py
- test_sqlalchemy.py
Implement proposal in #319 Specify Custom Query Class.
> Implement custom query and model class options

- .travis.yml
This adds the `sudo: false` config to speed up CI testing on TravisCI's new infrastructure.
> Use Travis' container-based infrastructure

- docs/models.rst
There is a place in the docs where it mentions overriding the table name, but doesn't explain how to do it. I added a clarification. There might be a better place for this or it may be better left out altogether (and kept to the SQLAlchemy docs)
> Clarify table name override attribute

- .gitmodules
Allows pip install from the git repository when the `git://` protocol is blocked.
In may environments, the `git://` protocol is blocked by the firewall. This causes
pip install -e git+https://github.com/mitsuhiko/flask-sqlalchemy.git#egg=Flask-SQLAlchemy
to fail since it will hang on submodule initialization.
> Change docs/_themes submodule protocol from git:// to https://

- flask_sqlalchemy/__init__.py
- test_sqlalchemy.py
`create_scoped_session` was using `partial` as the factory to `scoped_session`.  SQLAlchemy doesn't recognize this when listening to events, so it raises an exception.  Creating a `sessionmaker` in `create_session` fixes this.
sqlalchemy.exc.ArgumentError: Session event listen on a scoped_session requires that its creation callable is associated with the Session class.
Also changed `create_scoped_session` to include the default `scopefunc` and `query_cls`, since it would be pretty much pointless to manually use this function without those provided.
#182, #64, #147, #148
> Fix db.session so that events work

- docs/queries.rst
missing `.all()` in ordered query usage
> Fix wrong query usage in documentation

- flask_sqlalchemy/__init__.py
- test_sqlalchemy.py
Flask-SQLAlchemy is currently unable to handle defining a `__bind_key__` attribute on an abstract model. This change fixes that, and it includes an automated test.
> Support binds on abstract models

- .travis.yml
- test_sqlalchemy.py
- tox.ini
* `SQLALCHEMY_ENGINE` isn't a config key, so the default `sqlite://` was being used.
* `SQLALCHEMY_DATABASE_URI` defaults to `sqlite://` anyway, so just remove all these configs
* `CustomQueryClassTestCase` wasn't registered
* `CustomQueryClassTestCase.test_dont_override_model_default` wasn't testing the right thing, and was also failing
* `CustomModelClassTestCase` wasn't registered
* `import flask_sqlalchemy as sqlalchemy` is a confusing alias, used `fsa` instead
* added "lowest" and "current" tox envs for testing dependency versions
* Flask lowest tests against blinker==1.0, which doesn't have `connected_to`, replace with `connect` and `disconnect`
> Clean up tests, more thorough version testing

- flask_sqlalchemy/__init__.py
We should allow custom parameters for SQLALCHEMY_ECHO as we can expect 'debug' value
cf SQLAlchemy documentation: http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine.params.echo
> feat(echo): allow custom parameters for SQLALCHEMY_ECHO as 'debug'

- flask_sqlalchemy/__init__.py
With commit 9b5bd9427fb3562926b3f9d9f9401ea6159a1fb2 this comment became unclear since code was added below the comment which is actually unrelated to what the comment talks about.
> Move a source code comment to proper position

- AUTHORS
- docs/config.rst
From issue #401, adding additional documentation to help users configuring Flask-SQLAlchemy with a backends with a shorter idle connection timeout such as:
- MariaDB
- SAAS/IAAS provided databases that are pre-configured
I've included the error that generally indicates this is an issue `2013: Lost connection to MySQL server during query` so users googling the exception will have a better chance of finding appropriate documentation.
> Provide additional documentation for SQLALCHEMY_POOL_RECYCLE

- docs/contents.rst.inc
- docs/customizing.rst
This initial PR is a rough draft for providing documentation (as brought up in #396) on both the `query_class` and `model_class` options.  @augustjd if you care to weigh in on this as well for examples of what you'd like to see.
> Provide documentation for use of query_class

- flask_sqlalchemy/__init__.py
Since this attribute is not used anywhere in the implementation, we can
just delete it.
Otherwise, `app.extensions['sqlalchemy'].app` would be a circular
reference and cause memory leak.
> Avoid circular reference by deleting _SQLAlchemyState.app

- flask_sqlalchemy/__init__.py
next_num and prev_num simply increment or decrement the current page number. Obviously this leads to having invalid next and prev nums in the paginated object.
Using flask-restless, this error shows up in the api responses. This patch returns None if there is no next or previous, because this is the way flask-restless does it as well.
> Fix next_num and prev_num showing non existant page nums

- CHANGES
- flask_sqlalchemy/__init__.py
The db session is always tied to the app context and its teardown event.
Use `current_app` rather than examining the context stack directly.
Remove support for Flask < 0.10, which was already implied by the the requirements.
> Only use app context

- flask_sqlalchemy/__init__.py
- test_sqlalchemy.py
When examining model to generate tablename, only get `declared_attr` properties against the model, not all class properties.
Move tablename generation to the base `Model` to avoid SQLAlchemy warning about unmanaged access to declared attrs. (One test still raises this because abstract classes are unmanaged but still generate a name.)
`_BoundDeclarativeMeta` only handles popping off tablenames if they are manually set, so that subclasses still autogenerate. One side effect of this is that custom base models must inherit from the default base model (or re-implement the `__tablename__` declared attr), otherwise it would be impossible to set tablenames.
Thanks to @vToMy for helping come up with fixes. This patch is mostly based off their patch in …
> Don't access all class properties when generating tablename

- flask_sqlalchemy/__init__.py
Fixes #471 at https://github.com/mitsuhiko/flask-sqlalchemy/issues/471.
> Suppress warning about not set DATABASE_URI when SQLALCHEMY_BINDS are set

- flask_sqlalchemy/__init__.py
- tests/test_table_name.py
A tablename will be set for non-abstract classes unless a mixin defines one or a model or mixin defines a `declared_attr`.
`__table_cls__` executes at a time when all column and primary key constraints are known, and can decide not to set a table when the model looks like single-table inheritance. It will also unset a tablename in this case.
I haven't added tests for the issues yet, but this should eventually fix #470, fix #473, fix #478, fix #481, fix #492, fix #512, fix #533. 😣
CC @zzzeek, @ThiefMaster 
---
Previously:
~Goes back to performing all tablename behavior in `_BoundDeclarativeMeta`, instead of putting some in a `declared_attr`. It would be more accurate to diff this against 2.1.~
~If you define a primary key in a `declared_attr`, you have to mark that attr as a the primary …
> rewrite tablename generation again

- .codecov.yml
- .coveragerc
- .gitignore
- .travis.yml
- setup.cfg
- tox.ini
Based on Flask's configuration. Travis uses 3.6 and nightly instead of 3.6-dev. Travis reports to codecov. Tox adds docs and coverage report. Coverage uses branch coverage.
> update testing matrix, add coverage report

- flask_sqlalchemy/__init__.py
- flask_sqlalchemy/_compat.py
- tests/test_model_class.py
Add default `__repr__` for `Model` to reduce boilerplate
Fixes #528
> Add default __repr__ for Model class

- CHANGES
- docs/api.rst
- docs/customizing.rst
- flask_sqlalchemy/__init__.py
- flask_sqlalchemy/model.py
- tests/test_model_class.py
The original purpose for this was to be able to disable automatic tablename generation, but it became more general.
Previously, `model_class` needed to be a basic class, which would be passed to `declarative_base`. Now, if it is already the result of `declarative_base`, it is used directly. This allows greater customization by allowing the user to specify whatever arguments they want to `declarative_base`, including `metaclass`.
`_BoundDeclarativeMeta` has been renamed `DefaultMeta` since the previous name wasn't completely accurate. The `__bind_key__` and `__tablename__` behaviors are split into mixin classes that are both used to define `DefaultMeta`. Creating a metaclass without the `__tablename__` behavior looks like:
```python
from flask_sqlalchemy import SQLAlchemy
from …
```
> allow passing declarative_base as model_class

- CHANGES
- flask_sqlalchemy/__init__.py
- tests/test_binds.py
fixes #490 
If `init_app` was used and there were multiple apps registered, each connector and engine would use `current_app` instead of the actual app they were created for. Call `current_app._get_current_object()` to fix this.
> pass real app instead of current_app to connector

- CHANGES
- flask_sqlalchemy/model.py
- tests/test_table_name.py
If tables are already defined (or reflected), creating a model with an existing table name uses (or extends) that table. This worked in plain SQLAlchemy and 2.1, 2.2. `__table_cls__` needed to check for this.
fixes #550
> model uses existing table by name

- flask_sqlalchemy/model.py
- tests/test_model_class.py
This fixes issue #554 by printing an id of "None" before a model is persited to the database
> Fixes #554 representation of new model instances

- CHANGES
- flask_sqlalchemy/model.py
- tests/test_table_name.py
fixes #552 
```python
class User(db.Model):
name = db.Column(db.String)
```
```
sqlalchemy.exc.ArgumentError: Mapper Mapper|User|user could not assemble any primary key columns for mapped table 'user'
```
> raise correct error when model has name but no pkey

- CHANGES
- flask_sqlalchemy/__init__.py
- tests/test_pagination.py
Hey, in my application i used BaseQuery.paginate() method without any params and found that user can be able to use unlimited value for per_page param in http query. I think this param should be limited, here is the PR.
> limited per_page param in paginate

- CHANGES.rst
- flask_sqlalchemy/__init__.py
- tests/test_pagination.py
> set page and per_page defaults when invalid

- docs/config.rst
Addresses #469 -- adding windows example for URI configuration.
The current docs say
```
SQLite (note the four leading slashes):
sqlite:////absolute/path/to/foo.db
```
However, this can lead to unexpected results on Windows. This PR modifies the notes and adds windows examples with notes. Much like the counterpart [SQLAlchemy docs](http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlite)
> Add Windows example for sqlite URI configuration.

- docs/queries.rst
- docs/quickstart.rst
This is a couple of cases of repr() producing u-prefixes on strings and one instance of the print statement.
Seems fairly safe to assume that new users won't be on legacy Python so this updates the docs to be in line with what they'll see :)
> Python 3 tweaks in docs

- flask_sqlalchemy/__init__.py
- tests/test_pagination.py
Counting the length of a table can be slow on large tables   This PR makes that counting optional and is backwards compatible.  
Related:
https://github.com/mitsuhiko/flask-sqlalchemy/issues/518
https://github.com/mitsuhiko/flask-sqlalchemy/pull/281
> Optional count of total number of pages

- .travis.yml
- docs/conf.py
- examples/hello.py
- flask_sqlalchemy/__init__.py
- flask_sqlalchemy/model.py
- scripts/make-release.py
- setup.py
- tests/test_pagination.py
- tox.ini
This includes PR #588 ("Drop support for EOL Python 2.6") and therefore closes #588 and closes #587 and adds a single new commit to drop 3.3.
Python 3.3 is also EOL and used even less than 2.6.
Here's the pip installs for Flask-SQLAlchemy from PyPI for last month:
| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  83.31% |        468,134 |
| 3.6            |   9.90% |         55,611 |
| 3.5            |   4.43% |         24,867 |
| 3.4            |   2.20% |         12,369 |
| 2.6            |   0.07% |            420 |
| 3.7            |   0.06% |            342 |
| 3.3            |   0.03% |            186 |
| None           |   0.00% |              1 |
Source: `pypinfo --start-date -39 --end-date -12 --percent --pip …
> Drop support for EOL Python 2.6 and 3.3

- CHANGES.rst
- flask_sqlalchemy/model.py
- tests/test_binds.py
AttributeError: 'NoneType' object has no attribute 'info'
flask_sqlalchemy/model.py:124: AttributeError
How to reproduce:
```
bind_key = 'polymorphic_bind_key'
app.config['SQLALCHEMY_BINDS'] = {
bind_key: 'sqlite:///:memory',
}
class Base(db.Model):
__bind_key__ = bind_key
__tablename__ = 'base'
id = db.Column(db.Integer, primary_key=True)
p_type = db.Column(db.String(50))
__mapper_args__ = {
'polymorphic_identity': 'base',
'polymorphic_on': p_type
}
class Child1(Base):
child_1_data = db.Column(db.String(50))
__mapper_args__ = {
'polymorphic_identity': 'child_1',
}
```
> fix BindMetaMixin with polymorphic

- docs/queries.rst
- flask_sqlalchemy/__init__.py
- tests/test_query_property.py
Originally, `get_or_404` or `first_or_404` couldn't send the description about why that error happened. So I propose to add the description to the all `or_404` functions.
> Add description args for description of abort()

- tox.ini
When running with just `tox` you'd get the "lowest" library versions for the plain py27 run.
> Fix tox spec

- docs/config.rst
- flask_sqlalchemy/__init__.py
- flask_sqlalchemy/utils.py
- tests/test_basic_app.py
- tests/test_config.py
- tests/test_utils.py
- tox.ini
fixes #166 - make it possible to pass additional options to create_engine()
fixes #671, #681 - deprecation warnings from SA 1.3
> make SA engine configuration more flexible

- CHANGES.rst
- docs/config.rst
- flask_sqlalchemy/__init__.py
- tests/conftest.py
- tests/test_config.py
Resolves #699 
- Set `SQLALCHEMY_TRACK_MODIFICATIONS` to `False` by default
- Update tests to reflect new behavior
- Update pytest configuration to no longer set `app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False`
- Update `docs` to reflect new default
> Set SQLALCHEMY_TRACK_MODIFICATIONS to False by default

- CHANGES.rst
- docs/config.rst
- flask_sqlalchemy/__init__.py
- tests/test_config.py
Resolves #663 
- Default `SQLALCHEMY_DATABASE_URI` to `None` and throw an error when `SQLALCHEMY_DATABASE_URI` and `SQLALCHEMY_BINDS` are unset
- Update tests (`test_defaults` is now split into `test_default_error_without_uri_or_binds` and `test_defaults_with_uri`)
- Update 3.x docs for this change as well as tweaking change for https://github.com/pallets/flask-sqlalchemy/pull/727
- Update changelog and reformat change for https://github.com/pallets/flask-sqlalchemy/pull/727
> Default SQLALCHEMY_DATABASE_URI to None, error if no URI or binds

- flask_sqlalchemy/__init__.py
If you have duplicate results (which get deduped), `len(items)` always returns a value less than the per_page limit. This causes a bug whereby you have several pages of results, but the pagination metadata does not reveal this, and implies there is only one page of results.
The overhead from counting all results now, regardless of whether they fit onto a single page is worth considering, but using the `count ` flag can bypass this as before.
> Removed conditional count from pagination

- flask_sqlalchemy/__init__.py
Porting PR #804 into the 2.x release.
These two ways of counting the results fail spectacularly when there are duplicate results (which get de-duped). Discussed in that PR.
> Fixed bug with duplicate results and counting

- docs/quickstart.rst
It should be `Flask SQLAlchemy` Since we're talking about the differences between `Flask SQLAlchemy` and Pure `SQLAlchemy`
> distinguish SQLAlchemy class from SQLAlchemy library

- docs/quickstart.rst
Addresses #789 - the quickstart examples do what they say, this tries to clarify that `create_all` creating the SQLite database is coincidental and that in general it's a utility for creating tables in a database that already exists.
> clarify quickstart documentation regarding create_all

- CHANGES.rst
- src/flask_sqlalchemy/__init__.py
- tests/test_basic_app.py
Our microservices have deployment folders (with configuration files) that are separate from the repository folders. 
- The default sqlalchemy behavior for a relative sqlite path is to use the current working directory.
- However, flask-sqlalchemy assumes that all relative sqlite paths are relative to `app.root_path` and the resulting sqlite file ends up in the repository folder. Currently, we are using the following workaround to recreate the default sqlalchemy behavior:
```
SQLALCHEMY_DATABASE_URI = 'sqlite:///{data_folder}/database.sqlite'
APP.config['SQLALCHEMY_DATABASE_URI'] = APP.config[
'SQLALCHEMY_DATABASE_URI'].format(data_folder=os.getcwd())
```
As of 0.8, flask supports [instance folders](http://flask.pocoo.org/docs/0.12/config/#instance-folders). The proposed fix is to replace …
> Replace app.root_path with app.instance_path

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.rst
- README.rst
Resolves #723:
- Adds **Contributing** doc, links to it in the README
- Updates README to have a donate section to match Flask and other Pallets projects
Notes:
- The contributing document is based on [Flask's contributing document](https://github.com/pallets/flask/blob/master/CONTRIBUTING.rst)
- The contributing document is slightly different for testing and documentation instructions
> Add Contributing docs, add donate section to README

- docs/signals.rst
Added an explanation that tracking modifications is expensive, and recommended using SQLAlchemy's events directly.
closes #274
> link to sqlalchemy events in signals doc

- CHANGES.rst
- docs/config.rst
- flask_sqlalchemy/__init__.py
- tests/test_commit_on_teardown.py
Deprecate optional commit on teardown behavior. It is already disabled by default and at some point was removed from the config docs. #216 has has a lot of discussion on why this is unreliable and causes design issues. It will be removed in version 3.1, but I'll release this as 2.4.3 so the warning can be shown for longer.
closes #216
> deprecate COMMIT_ON_TEARDOWN

- CHANGES.rst
- flask_sqlalchemy/model.py
This fixes regression introduced in Python 3.8.4, fixes #852 
All unit tests passed on Python 3.8.4:
```
tox -epy38
GLOB sdist-make: /app/setup.py
py38 inst-nodeps: /app/.tox/.tmp/package/1/Flask-SQLAlchemy-2.4.3.zip
py38 installed: attrs==19.3.0,blinker==1.4,click==7.1.2,coverage==5.2,Flask==1.1.2,Flask-SQLAlchemy @ file:///app/.tox/.tmp/package/1/Flask-SQLAlchemy-2.4.3.zip,itsdangerous==1.1.0,Jinja2==2.11.2,MarkupSafe==1.1.1,mock==4.0.2,more-itertools==8.4.0,packaging==20.4,pluggy==0.13.1,py==1.9.0,pyparsing==2.4.7,pytest==5.4.3,six==1.15.0,SQLAlchemy==1.3.18,wcwidth==0.2.5,Werkzeug==1.0.1
py38 run-test-pre: PYTHONHASHSEED='992667399'
py38 run-test: commands[0] | coverage run -p -m pytest --tb=short --basetemp=/app/.tox/py38/tmp
=============================== test session starts …
```
> Subclass meta mixins from `type`

- docs/quickstart.rst
This PR originated in [this issue](https://github.com/pallets/flask/issues/3865). In my opinion, the missing of the installation instruction may confused Python beginners.
> Add Installation section in Quickstart

- CHANGES.rst
- src/flask_sqlalchemy/model.py
- tests/test_sessions.py
- tests/test_table_name.py
I have updated the regex pattern for converting CamelCase table names to snake_case. I've also compared this with #617. Detailed results of the comparison can be found [here](http://bit.ly/test-case-analysis). 
`tests/test_basic_app.py::test_sqlite_relative_path` fails for `SQLAlchemy == 1.4.0` giving #885. All tests pass with older `SQLAlchemy` version.
- fixes #406 
Checklist:
> Updated CamelCase to snake_case converter to cover more cases

- CHANGES.rst
- src/flask_sqlalchemy/__init__.py
In MySQL 8, the `utf8` charset alias to `utf8mb3` (deprecated), and will be an alias to `utf8mb4` (default value) in the future releases, so it's better to change it to `utf8mb4` explicitly ([ref](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-sets.html)).
- fixes #875
Checklist:
> Change the default MySQL charset to utf8mb4

- CHANGES.rst
- src/flask_sqlalchemy/pagination.py
- src/flask_sqlalchemy/query.py
- tests/test_pagination.py
fixes #1091 
* `per_page` cannot be 0.
* `max_per_page` defaults to 100.
> pagination tweaks

- CHANGES.rst
- src/flask_sqlalchemy/extension.py
- tests/test_engine.py
If the SQLite URL has `uri=true` in the query, it is a "driver-level URI" that will start with `file:`, like `sqlite:///file:path.db?uri=true`. Detect this when checking relative paths and creating the instance folder.
fixes #998
fixes #1045
> sqlite driver-level uri

- CHANGES.rst
- docs/pagination.rst
- src/flask_sqlalchemy/pagination.py
- tests/test_pagination.py
Adds `first` and `last` properties to `Pagination`. These give the number of the first and last item on the page, so you can display something like `showing first - last of total`.
fixes #567
> pagination first and last item number

- src/flask_sqlalchemy/__init__.py
This is the first prerelease to preview the changes in 3.0. There were significant changes in #1087, see the changelog for a full list. Many of those changes will raise deprecation warnings, but it was not feasible to implement warnings for some things. The prereleases are an opportunity to report any breaking changes *that can't be adapted to*.
> prerelease 3.0.0a1

- .github/workflows/tests.yaml
- src/flask_sqlalchemy/extension.py
- tests/test_metadata.py
If `model_class` is a fully created declarative base, use its `metadata` as the default metadata instead of replacing it with another blank one. If both `metadata` and `model_class` are passed in, the custom metadata will be used, replacing the model's.
Otherwise, you'd need to pass the metadata twice, like `SQLAlchemy(model_class=declarative_base(metadata=metadata), metadata=metadata)`, to get the model and extension to use the custom metadata. Now you can leave off the metadata argument to the extension.
> use metadata from custom declarative base class

- CHANGES.rst
- docs/config.rst
- src/flask_sqlalchemy/__init__.py
- src/flask_sqlalchemy/extension.py
- src/flask_sqlalchemy/model.py
- src/flask_sqlalchemy/record_queries.py
* Remove compatibility aliases for moved or renamed imports.
* Remove `COMMIT_ON_TEARDOWN`.
* Remove setting bind key through `Table.info`.
* Remove `get_engine`, `get_tables_for_bind`, and `get_binds` methods.
* Remove `db.db` alias.
* Remove `context` alias and tuple behavior from recorded query info objects.
> remove previously deprecated code

- .github/workflows/tests.yaml
* PDM fixed compatibility with importlib-metadata, remove the restriction.
* Remove the PyPy CI env, we don't do anything specific to PyPy and it's the slowest test.
* Add a "lowest requirements" CI env, that runs `tox -e py310-lowest`. This helps remain compatible with the lowest supported versions of Flask and SQLAlchemy.
* Enable PDM's install cache and restore it with actions/cache.
> update CI config, cache PDM

- CHANGES.rst
Export typing information instead of using typeshed.
MyPy and PyRight both show an error when inheriting from `db.Model`. However, based on the discussion in #1112, the user experience should be the same whether we stick with typeshed or export our own types.
These are the relevant MyPy and PyRight issues. If you don't like that you need to ignore every `class User(db.Model)` line, you'll need to provide feedback to those projects.
- https://github.com/python/mypy/issues/8603
- https://github.com/microsoft/pyright/issues/2058
closes #1112
> add py.typed marker

- CHANGES.rst
- src/flask_sqlalchemy/extension.py
- tests/test_engine.py
If default engine options were set, but `SQLALCHEMY_DATABASE_URI` was not, engine options for the default bind could be added without a URL, causing a `KeyError` during configuration. Now, the default bind config is not added if it doesn't have a `"url"` key.
fixes #1117
> skip invalid default bind

- CHANGES.rst
- src/flask_sqlalchemy/extension.py
- tests/test_engine.py
- tests/test_legacy_query.py
- tests/test_model_name.py
A few changes in the latest SQLAlchemy 2 preview:
- SQLAlchemy no longer sets `__all__`.
- SQLite uses `QueuePool` instead of `NullPool`.
- Ignore `LegacyAPIWarning` when testing the legacy API. The lowest supported version, 1.4.18, does not have this class.
- Can't use `sa.Column[sa.Integer]` as a type, ignore it in the one test that uses it.
fixes #1122
> update compatibility with sqlalchemy 2

- docs/pagination.rst
Corrects argument references in the example macro in pagination.
- fixes #1126
> Use the pagination parameter

- CHANGES.rst
- src/flask_sqlalchemy/extension.py
- tests/test_metadata.py
Show an error for an invalid pattern which worked by accident but stopped in version 3. The user creates multiple extension instances, usually in different modules or during tests, rather than importing a single instance. If they fail to call ``init_app`` on one, the extension can't find the app in its engine registry. Or if they call ``init_app`` on both they can end up with conflicting sessions.
> show errors on multiple instances or missing init

- CHANGES.rst
- setup.cfg
- src/flask_sqlalchemy/session.py
- tests/test_session.py
`get_bind` uses `mapper.local_table`. Previously it used `persist_selectable`, which was a join clause instead of a table for polymorphic table models, so it didn't have a `metadata` to look up the bind key on.
> fix `get_bind` with polymorphic table inheritance

- docs/binds.rst
The `bind` param in `create_all()` was renamed to `bind_key` in 3.x.
> Fix outdated parameter names in the binds docs

- docs/customizing.rst
I believe there was a typo in the documentation, as `Model` is used later in the code, and `flask_sqlalchemy.model.model` is not an actual object you can import
> Fixed documentation typo

- docs/contexts.rst
The `app` argument is no longer needed in the `test_user_model()`  once the context of the app is loaded by `app_ctx` fixture, so removing the `app` argument will make the intent of this example more clear. Additionally, `pytest.mark.fixture` is not available in the latest Pytest. I replace it with `pytest.fixture`.
**Only the docs were changed**.
> Docs change: Make the intent of the example more clear

- CHANGES.rst
- src/flask_sqlalchemy/pagination.py
- tests/test_pagination.py
The `Pagination` `max_per_page` value should be carried into the next `Pagination` object when calling `next()`
- fixes #1201
Checklist:
> Pagination per_page gets wrong value after calling next() #1201

- CHANGES.rst
- src/flask_sqlalchemy/extension.py
- tests/test_view_query.py
Thanks to a new test in main, I discovered that the return type of get_or_404 should *not* be Optional. I had chosen Optional since it can raise exceptions, but I've now learnt that Python typing does not document exception raising.
Checklist:
> Improve type hint

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
- CHANGES.rst
- examples/flaskr/setup.cfg
- pyproject.toml
- tox.ini
This drops support for Python 3.7 which has reached EOL
Checklist:
~- [ ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.~
~- [ ] Add or update relevant docs, in the docs folder and in code.~
~- [ ] Add `.. versionchanged::` entries in any relevant code docs.~
> drop Python 3.7 support

- examples/flaskr/README.rst
- examples/flaskr/flaskr/__init__.py
- examples/flaskr/flaskr/auth/models.py
- examples/flaskr/flaskr/blog/models.py
- examples/flaskr/setup.cfg
- examples/todo/app.py
This PR updates the Flaskr and todo sample apps to use 2.0 style models. All flaskr tests pass.
Checklist:
~- [ ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.~
~- [ ] Add or update relevant docs, in the docs folder and in code.~
~- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.~
~- [ ] Add `.. versionchanged::` entries in any relevant code docs.~
> Update flaskr and todo to use SQLAlchemy 2.0 style

- CHANGES.rst
- src/flask_sqlalchemy/session.py
- tests/test_session.py
- fixes #1210
Checklist:
- [  ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
> Fixed clause_to_engine bug not finding the right db bind key

- CHANGES.rst
- pyproject.toml
- src/flask_sqlalchemy/__init__.py
The `__version__` attribute is an old pattern from early in Python packaging. Setuptools eventually made it easier to use the pattern by allowing reading the value from the attribute at build time, and some other build backends have done the same.
However, there's no reason to expose this directly in code anymore. It's usually easier to use feature detection (`hasattr`, `try/except`) instead. `importlib.metadata.version("flask-sqlalchemy")` can be used to get the version at runtime in a standard way, if it's really needed.
> deprecate __version__ attribute

- CHANGES.rst
Hey,
I found a wrong link in the changelog and here is the fix.
You can find the original PR here:
https://github.com/pallets-eco/flask-sqlalchemy/pull/1256
An issue wasn't linked so I changed the link to be redirecting to a PR.
Cheers,
Damian
> Fix PR id in the changelog

- README.rst
- docs/customizing.rst
- docs/models.rst
- docs/pagination.rst
- docs/quickstart.rst
This PR made some code improvements in docs:
* Changed column to declarations to leave off column type since it's inferred from the type annotations.
* Moved from utcnow to now, which Python docs recommend: https://docs.python.org/3/library/datetime.html#datetime.datetime.now
* Fixed missing quotes in HTML
> refactor docs

- .github/workflows/tests.yaml
- docs/models.rst
- tests/test_metadata.py
This PR adds "(db.Model)" to reflection docs example. I also added to the reflection test to mirror the documentation example, and I put an additional example in the docs showing default bind key. 
- fixes #1280
Checklist:
~- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.~
~- [ ] Add `.. versionchanged::` entries in any relevant code docs.~
> Fixing missing base class in reflection docs, adding to reflection test

- .github/workflows/tests.yaml
- CHANGES.rst
- src/flask_sqlalchemy/extension.py
- tests/test_extension_repr.py
This PR adds test for SQLAlchemy's repr and fixes its handling of the no default engine scenario. 
This fix assumes we want engine() to continue to throw a KeyError in that scenario (i.e. all handling is in repr itself).
- fixes #1295
Checklist:
> Fix repr and add tests

- docs/config.rst
Just a fix for a typo in the documentation.
> Fix typo in "SQAlchemy" in docs
