test_sqlalchemy.py

Reverts mitsuhiko/flask-sqlalchemy#236

Revert "Test case for before_models_committed"

---

tox.ini

Seems appropriate for the time.

Add python 3.4 to tox.ini

---

docs/contexts.rst

I got stuck on the wording and am hoping others may benefit from these fixes.

Fix docs/contexts.rst

---

flask_sqlalchemy/__init__.py

https://github.com/mitsuhiko/flask-sqlalchemy/issues/421

warn user when SQLALCHEMY_DATABASE_URI is not set

---

docs/contexts.rst
flask_sqlalchemy/__init__.py

add app context error message to docs
add link to docs to error message
fixes #553

document app context error message

---

README.rst

User first argument should be username rather than name

fix typo in Simple Example

---

CODE_OF_CONDUCT.md

- Addition of Code Of Conduct as is been added in other Pallet Projects.
- Solves #732

Addition of COC in reference to other Pallet Projects

---

CHANGES.rst
flask_sqlalchemy/model.py
tests/test_binds.py

cherry picked from commit 5a3422e01fa63062dad7bc0f98943c5934a05bb6
related to #778

backport #651 fix BindMetaMixin with polymorphic

---

.travis.yml
CHANGES.rst
docs/index.rst
setup.py
tox.ini

bump minimum flask and sqlalchemy versions

---

.editorconfig
.github/ISSUE_TEMPLATE.md
.github/workflows/tests.yaml
.pre-commit-config.yaml
docs/binds.rst
docs/conf.py
docs/config.rst
examples/flaskr/flaskr/auth/__init__.py
examples/flaskr/flaskr/blog/__init__.py
examples/hello/hello.py
setup.cfg
src/flask_sqlalchemy/__init__.py
src/flask_sqlalchemy/model.py
tests/conftest.py
tests/test_basic_app.py
tests/test_binds.py
tests/test_commit_on_teardown.py
tests/test_config.py
tests/test_meta_data.py
tests/test_model_class.py
tests/test_pagination.py
tests/test_query_class.py
tests/test_query_property.py
tests/test_regressions.py
tests/test_sessions.py
tests/test_signals.py
tests/test_sqlalchemy_includes.py
tests/test_table_name.py
tox.ini

* [pyupgrade](https://github.com/asottile/pyupgrade)
* [reorder-python-imports](https://github.com/asottile/reorder_python_imports)
* [black](https://github.com/psf/black/)
* [flake8](https://gitlab.com/pycqa/flake8), [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear), [flake8-implicit-str-concat](https://github.com/keisheiled/flake8-implicit-str-concat)
* [pre-commit](https://pre-commit.com/)
* [EditorConfig](https://editorconfig.org/)
You should install the pre-commit hooks in your local repository so the checks are run before each commit. They will also be run by `tox` and CI.

apply style tools

---

docs/customizing.rst

This proposed change fixes #815

Removed unused import from customizing example

---

docs/quickstart.rst

Add 'self' to '__init__' method

---

docs/conf.py
docs/contexts.rst
docs/index.rst
examples/flaskr/README.rst
src/flask_sqlalchemy/__init__.py
tests/test_config.py

pocoo.org --> palletsprojects.com

Update old Pocoo links

---

CHANGES.rst
flask_sqlalchemy/__init__.py
tests/test_config.py

Support SQLAlchemy 1.4

---

flask_sqlalchemy/__init__.py

Copy Werkzeug's ident_func

---

CHANGES.rst
flask_sqlalchemy/__init__.py

get_ident compat for Python 2.7

---

src/flask_sqlalchemy/__init__.py

just added line from SQLAlchemy docs ([link](https://docs.sqlalchemy.org/en/13/core/metadata.html#sqlalchemy.schema.MetaData.create_all)) that seems germane i.e. "create_all(), idempotent, yay or nay?"

add more detailed description for create_all

---

docs/quickstart.rst

Port installation guide from main to 2.x

---

CHANGES.rst
src/flask_sqlalchemy/cli.py
src/flask_sqlalchemy/extension.py
tests/test_cli.py

add db and models to flask shell

---

CHANGES.rst
docs/config.rst
src/flask_sqlalchemy/extension.py
src/flask_sqlalchemy/record_queries.py
tests/test_record_queries.py

no automatic SQLALCHEMY_RECORD_QUERIES

---

CHANGES.rst
src/flask_sqlalchemy/extension.py

mysql no pool_recycle if not queue pool

---

src/flask_sqlalchemy/extension.py
tests/test_model.py

set model.query when using custom declarative base

---

CONTRIBUTING.rst

Updates steps per discussion with @davidism while releasing 3.0.4 today.
Checklist:

Update contributing guidelines

---

README.md

There are three updates:
- drop the table before create it, to fix the `UNIQUE constraint failed` error  when re-run the example code.
- change username `example` to `frank` to fit better with person's name.
- use shorthand `scalars()` method and print all usernames.

Improve the example in README.md
